"""Delete column

Revision ID: 13fbe4befb7e
Revises: 629ee011e3d4
Create Date: 2022-05-28 09:36:35.685886

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '13fbe4befb7e'
down_revision = '629ee011e3d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock', 'side')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('side', postgresql.ENUM('buy', 'sell', name='side'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
