"""Fix Item model

Revision ID: 637e5988f375
Revises: d371cbacadcd
Create Date: 2022-05-29 10:37:49.883060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '637e5988f375'
down_revision = 'd371cbacadcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('stock_id', sa.Integer(), nullable=True))
    op.add_column('item', sa.Column('qty', sa.Float(), nullable=True))
    op.drop_index('ix_item_description', table_name='item')
    op.drop_index('ix_item_title', table_name='item')
    op.create_foreign_key(None, 'item', 'stock', ['stock_id'], ['id'])
    op.drop_column('item', 'description')
    op.drop_column('item', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('item', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.create_index('ix_item_title', 'item', ['title'], unique=False)
    op.create_index('ix_item_description', 'item', ['description'], unique=False)
    op.drop_column('item', 'qty')
    op.drop_column('item', 'stock_id')
    # ### end Alembic commands ###
