"""Add model Signal and change Stock

Revision ID: c12aae1735e9
Revises: df978b26c5d4
Create Date: 2022-05-28 08:27:12.081851

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c12aae1735e9'
down_revision = 'df978b26c5d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_datetime', sa.DateTime(), nullable=True),
    sa.Column('text', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_id'), 'signal', ['id'], unique=False)
    op.add_column('stock', sa.Column('ticker', sa.String(), nullable=True))
    op.add_column('stock', sa.Column('country', sa.String(), nullable=True))
    op.add_column('stock', sa.Column('url', sa.String(), nullable=True))
    op.add_column('stock', sa.Column('desc', sa.String(), nullable=True))
    op.add_column('stock', sa.Column('price', sa.Float(), nullable=True))
    op.add_column('stock', sa.Column('signal_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_stock_country'), 'stock', ['country'], unique=False)
    op.create_index(op.f('ix_stock_ticker'), 'stock', ['ticker'], unique=False)
    op.create_foreign_key(None, 'stock', 'signal', ['signal_id'], ['id'])
    op.drop_column('stock', 'for_buy')
    op.drop_column('stock', 'for_sell')
    op.drop_column('stock', 'created_datetime')
    op.drop_column('stock', 'text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('stock', sa.Column('created_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('stock', sa.Column('for_sell', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('stock', sa.Column('for_buy', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'stock', type_='foreignkey')
    op.drop_index(op.f('ix_stock_ticker'), table_name='stock')
    op.drop_index(op.f('ix_stock_country'), table_name='stock')
    op.drop_column('stock', 'signal_id')
    op.drop_column('stock', 'price')
    op.drop_column('stock', 'desc')
    op.drop_column('stock', 'url')
    op.drop_column('stock', 'country')
    op.drop_column('stock', 'ticker')
    op.drop_index(op.f('ix_signal_id'), table_name='signal')
    op.drop_table('signal')
    # ### end Alembic commands ###
