"""Add column side

Revision ID: d371cbacadcd
Revises: 13fbe4befb7e
Create Date: 2022-05-28 09:37:18.740693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd371cbacadcd'
down_revision = '13fbe4befb7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('side', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock', 'side')
    # ### end Alembic commands ###
