"""Add model Stock

Revision ID: df978b26c5d4
Revises: 9d3996d58dff
Create Date: 2022-05-28 06:27:33.138975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df978b26c5d4'
down_revision = '9d3996d58dff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock', 'text')
    # ### end Alembic commands ###
